import React, { createContext, useContext, useState, useEffect } from "react";

export const LanguageContext = createContext();

export const translations = {
  EN: {
    // Header
    login: "Login",
    navLatest: "Latest Projects",
    navPremium: "Premium Selection",
    navMap: "Villas Map",
    navNews: "Market News",
    inquiry: "Inquiry",

    // Banner
    bannerTitle: "More than just walls",
    bannerSubtitle: "Discover a life of harmony",
    bannerLocation: "Location",
    bannerLocationValue: "Riyadh, SA",
    bannerCheckIn: "Check In",
    bannerCheckOut: "Check Out",
    bannerDates: "Add Dates",
    bannerRooms: "Rooms and Guests",
    bannerRoomsValue: "1 rooms, 1 adults",
    bannerSearch: "Search",
    bannerAll: "All",
    bannerVillas: "Villas",
    bannerApartments: "Apartments",
    bannerEstates: "Estates",
    bannerPenthouses: "Penthouses",
    bannerTownhouses: "Townhouses",

    // LatestProjects
    latestProjects: "Latest Projects",
    viewAll: "View All Projects",
    beds: "Beds",
    baths: "Baths",
    soldStatus: "Sold Status",

    // PremiumListing
    premiumListing: "Premium Listing",
    premiumInquiry: "Inquiry & Concierge",
    premiumCurate: "Let Us Curate Your Dream Lifestyle",
    premiumRequestInfo: "Request Information",
    premiumSubtitle: "Our experts will get back to you within 24 hours to provide a personalized consultation.",
    premiumName: "Full Name",
    premiumPhone: "Phone Number",
    premiumEmail: "Email Address",
    premiumInterest: "Interest",
    premiumMessage: "Your Message...",
    premiumSend: "SEND INQUIRY",
    premiumSuccess: "Request Received",
    premiumSuccessMsg: "Thank you for your interest. One of our premium consultants will reach out to you shortly.",
    premiumBack: "Back to Form",

    // Map Section
    mapTitle: "Top Sign To See",
    mapLocationOverview: "Selected Location",
    mapFilters: "Search Filters",
    mapStatus: "Project Status",
    mapReset: "Reset All",
    mapNoResults: "No Matching Villas",
    mapNoResultsSub: "Try adjusting your filters or status selection to see more results.",
    bookViewing: "Book Viewing",
    Buy: "Buy",
    Rent: "Rent",
    "Buy Property": "Buy Property",
    "Rent Property": "Rent Property",
    "Submit Buy Request": "Submit Buy Request",
    "Submit Rent Request": "Submit Rent Request",
    Success: "Success",
    moveInDate: "Move-in Date",
    duration: "Duration",
    optional: "Optional",
    Close: "Close",
    available: "Available",
    availableProperties: "Available Villas",
    salePrice: "Sale Price",
    rentalPrice: "Rental Price",

    // News
    latestNews: "Latest News",
    readMore: "Read More",

    // Footer
    footerDescription: "RIYADHRF Real Estate excels in modern real estate marketing, leveraging a vast client database and expert team to promote projects effectively.",
    footerQuickLinks: "Quick Links",
    footerServices: "Services",
    footerContact: "Contact",
    footerInterested: "Interested?",
    footerRights: "© 2025 RiyadhRoof. All rights reserved.",
    footerHome: "Home",
    footerProjects: "Projects",
    footerDevelopers: "Developers",
    footerNews: "News",
    footerOffPlan: "Off-plan sales",
    footerLands: "Lands",
    footerCashback: "Ramadan Cashback",
    footerApproach: "Our Approach",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms & Conditions",


    // Navbar new links
    navSale: "Sale",
    navRent: "Rent",
    navNewBuildings: "New Buildings",
    navSpecialOffers: "Special Offers",

    // Search form
    formBuy: "Buy",
    formRent: "Rent",
    formType: "Property Type",
    formCity: "City",
    formRooms: "Rooms",
    formAny: "Any",
    formPriceFrom: "Price from",
    formPriceTo: "Price to",
    formSearch: "Search",
    formApartment: "Apartment",
    formVilla: "Villa",
    formTownhouse: "Townhouse",
    formCommercial: "Commercial",
    formLand: "Land",
    checkHasPhoto: "Has photo",
    checkNewBuilding: "New building",
    checkFromOwner: "From owner",
    checkCommercialFilter: "Commercial",
    Contact: "Contact",

    // Special Offers
    specialOffers: "Special Offers",
    specialOffersSubtitle: "Promotions and exclusive deals for you.",
    offerCta: "View Offer",

    // Hot Deals
    hotDeals: "Hot Deals",
    hotDealsSubtitle: "Real estate listings in Riyadh",
    hotDealsSale: "For Sale",
    hotDealsRent: "For Rent",
    hotDealsApartments: "Apartments",
    hotDealsLands: "Lands",
    hotDealsVillas: "Villas",
    hotDealsCommercial: "Commercial",
    hotDealsRooms: "Rooms",
    hotDealsViewAll: "View all",
    returnToProjects: "Return",

    // Special Offer content
    offer1Tagline: "Seasonal Offer",
    offer1Headline: "Great conditions. Great villa.",
    offer1Desc: "Save 15% on a villa with a city view — this month only.",
    offer2Tag: "New Building",
    offer2Tagline: "Direct from developer",
    offer2Headline: "Modern apartment in KAFD.",
    offer2Desc: "Apartments in Riyadh's financial district with up to 5-year installments.",
    offer3Tag: "Exclusive",
    offer3Tagline: "Only with us",
    offer3Headline: "Penthouse at Al Narjis Heights.",
    offer3Desc: "Panoramic views, private terrace, full finishing. Best price of the season.",

    // Advanced search
    moreSettings: "More settings",
    lessSettings: "Less settings",
    clearAll: "Clear all",
    showResults: "Show results",
    viewList: "List",
    viewMap: "Map",
    houseType: "House type",
    yearBuilt: "Year built",
    floor: "Floor",
    notFirst: "Not first",
    notLast: "Not last",
    totalArea: "Total area, m²",
    kitchenArea: "Kitchen area, m²",
    resComplex: "Residential complex",
    hotOffers: "Hot Offers",
    viewAllOffers: "View all",
    sortBy: "Sort by:",
    sortNew: "Newest",
    sortCheap: "Cheapest",
    sortExpensive: "Expensive",
    searchInThisSection: "Submit ad in this section",
    foundAds: "ads found",
    from: "From",
    to: "To",
    any: "Any",
    Analytics: "Analytics",
    priceAnalytics: "Market Analytics",
    rentVsSale: "Rent vs Sale",
    averagePrice: "Average Price",
    marketTrends: "Market Trends",
    yearlyGrowth: "Yearly Growth",
    villaSales: "Villa Sales",
    villaRentals: "Villa Rentals",
    available: "Available",
    forSale: "For Sale",
    forRent: "For Rent",
    liveData: "Live Market Data",
    activeBuyers: "Active Buyers",
    monthlyPerformance: "Monthly Performance",
    units: "units",
    projectedGrowth: "Projected Market Growth",
    marketPrediction: "Market prediction indicates a strong 15% growth in the North Riyadh sector by Q4 2025.",

    Authenticated: "Authenticated",
    Logout: "Logout",
    Profile: "Profile",
    InfinityPool: "Infinity Pool",
    SmartHome: "Smart Home",
    HomeGym: "Home Gym",
    Security: "Security 24/7",
    GardenArea: "Garden Area",
    PrivateParking: "Private Parking",
    Wifi: "High-Speed WiFi",
    AC: "Air Conditioning",
    Location: "Location",
    Riyadh: "Riyadh",
    AboutProperty: "About Property",

  },
  RU: {
    login: "Войти",
    navLatest: "Проекты",
    navPremium: "Премиум",
    navMap: "Карта вилл",
    navNews: "Новости рынка",
    inquiry: "Запрос",

    bannerTitle: "Больше, чем просто стены",
    bannerSubtitle: "Откройте для себя жизнь в гармонии",
    bannerLocation: "Местоположение",
    bannerLocationValue: "Эр-Рияд, СА",
    bannerCheckIn: "Заезд",
    bannerCheckOut: "Выезд",
    bannerDates: "Добавить даты",
    bannerRooms: "Комнаты и гости",
    bannerRoomsValue: "1 комната, 1 взрослый",
    bannerSearch: "Поиск",
    bannerAll: "Все",
    bannerVillas: "Виллы",
    bannerApartments: "Апартаменты",
    bannerEstates: "Поместья",
    bannerPenthouses: "Пентхаусы",
    bannerTownhouses: "Таунхаусы",

    latestProjects: "Последние проекты",
    viewAll: "Все проекты",
    beds: "Спальни",
    baths: "Ванные",
    soldStatus: "Продано",

    premiumListing: "Премиум объявления",
    premiumInquiry: "Запрос и Консьерж",
    premiumCurate: "Создадим стиль вашей мечты",
    premiumRequestInfo: "Запросить информацию",
    premiumSubtitle: "Наши эксперты ответят вам в течение 24 часов для персональной консультации.",
    premiumName: "Полное имя",
    premiumPhone: "Номер телефона",
    premiumEmail: "Email адрес",
    premiumInterest: "Интерес",
    premiumMessage: "Ваше сообщение...",
    premiumSend: "ОТПРАВИТЬ ЗАПРОС",
    premiumSuccess: "Запрос получен",
    premiumSuccessMsg: "Спасибо за ваш интерес. Один из наших консультантов свяжется с вами в ближайшее время.",
    premiumBack: "Вернуться к форме",

    mapTitle: "Лучшие предложения",
    mapLocationOverview: "Выбранная локация",
    mapFilters: "Фильтры поиска",
    mapStatus: "Статус проекта",
    mapReset: "Сбросить все",
    mapNoResults: "Виллы не найдены",
    mapNoResultsSub: "Попробуйте изменить фильтры или выбор статуса, чтобы увидеть больше результатов.",
    bookViewing: "Записаться на просмотр",
    Buy: "Купить",
    Rent: "Арендовать",
    "Buy Property": "Покупка жилья",
    "Rent Property": "Аренда жилья",
    "Submit Buy Request": "Отправить запрос",
    "Submit Rent Request": "Отправить запрос",
    Success: "Успешно",
    moveInDate: "Дата заезда",
    duration: "Срок аренды",
    optional: "необязательно",
    Close: "Закрыть",

    latestNews: "Последние новости",
    readMore: "Читать далее",

    footerDescription: "RIYADHRF Real Estate преуспевает в современном маркетинге недвижимости, используя обширную клиентскую базу для эффективного продвижения проектов.",
    footerQuickLinks: "Ссылки",
    footerServices: "Услуги",
    footerContact: "Контакты",
    footerInterested: "Интересует?",
    footerRights: "© 2025 RiyadhRoof. Все права защищены.",
    footerHome: "Главная",
    footerProjects: "Проекты",
    footerDevelopers: "Застройщики",
    footerNews: "Новости",
    footerOffPlan: "Продажи вне плана",
    footerLands: "Земли",
    footerCashback: "Рамадан Кэшбэк",
    footerApproach: "Наш подход",
    footerPrivacy: "Политика конфиденциальности",
    footerTerms: "Условия и положения",

    navSale: "Продажа",
    navRent: "Аренда",
    navNewBuildings: "Новостройки",
    navSpecialOffers: "Спецпредложения",
    returnToProjects: "Вернуться",
    avaible: "Доступный",
    availableProperties: "Доступные виллы",

    salePrice: "Цена продажи",
    rentalPrice: "Цена аренды",
    Contact: "Контакт",
    Authenticated: "Проверено",
    Logout: "Выйти",
    Profile: "Профиль",
    Location: "Местоположение",
    Riyadh: "Эр-Рияд",
    AboutProperty: "Описание",

    InfinityPool: "Бассейн",
    SmartHome: "Умный дом",
    HomeGym: "Домашний спортзал",
    Security: "Охрана 24/7",
    GardenArea: "Садовая зона",
    PrivateParking: "Частная парковка",
    Wifi: "Высокоскоростной Wi-Fi",
    AC: "Кондиционер",



    formBuy: "Купить",
    formRent: "Снять",
    formType: "Тип недвижимости",
    formCity: "Город",
    formRooms: "Комнаты",
    formAny: "Любое",
    formPriceFrom: "Цена от",
    formPriceTo: "Цена до",
    formSearch: "Найти",
    formApartment: "Квартира",
    formVilla: "Вилла",
    formTownhouse: "Таунхаус",
    formCommercial: "Коммерческое",
    formLand: "Земельный участок",
    checkHasPhoto: "Есть фото",
    checkNewBuilding: "Новостройка",
    checkFromOwner: "От хозяина",
    checkCommercialFilter: "Коммерческие",

    specialOffers: "Спецпредложения",
    specialOffersSubtitle: "Акции, скидки и специальные предложения для вас.",
    offerCta: "Подробнее",

    hotDeals: "Горячие предложения",
    hotDealsSubtitle: "Объявления о недвижимости в Эр-Рияде",
    hotDealsSale: "Продажа",
    hotDealsRent: "Аренда",
    hotDealsApartments: "Квартиры",
    hotDealsLands: "Участки",
    hotDealsVillas: "Виллы",
    hotDealsCommercial: "Коммерческая",
    hotDealsRooms: "Комнаты",
    hotDealsViewAll: "Смотреть все",

    offer1Tagline: "Сезонное предложение",
    offer1Headline: "Отличные условия. Отличная вилла.",
    offer1Desc: "Скидка 15% на виллу с видом на город — только до конца месяца.",
    offer2Tag: "Новостройка",
    offer2Tagline: "Прямая продажа от застройщика",
    offer2Headline: "Современный апартамент в KAFD.",
    offer2Desc: "Апартаменты в финансовом районе Эр-Рияда с рассрочкой до 5 лет.",
    offer3Tag: "Эксклюзив",
    offer3Tagline: "Только у нас",
    offer3Headline: "Пентхаус в Al Narjis Heights.",
    offer3Desc: "Панорамный вид, частная терраса, полная отделка. Лучшая цена сезона.",

    // Advanced search
    moreSettings: "Ещё настройки",
    lessSettings: "Свернуть",
    clearAll: "Очистить всё",
    showResults: "Показать результаты",
    viewList: "Списком",
    viewMap: "На карте",
    houseType: "Тип дома",
    yearBuilt: "Год постройки",
    floor: "Этаж",
    notFirst: "Не первый",
    notLast: "Не последний",
    totalArea: "Общая площадь, м²",
    kitchenArea: "Площадь кухни, м²",
    resComplex: "Жилой комплекс",
    hotOffers: "Горячие предложения",
    viewAllOffers: "Смотреть все",
    sortBy: "Сначала:",
    sortNew: "Новые",
    sortCheap: "Дешевые",
    sortExpensive: "Дорогие",
    searchInThisSection: "Подать объявление в этот раздел",
    foundAds: "объявлений найдено",
    from: "От",
    to: "До",
    any: "Любое",
    Analytics: "Аналитика",
    priceAnalytics: "Аналитика рынка",
    rentVsSale: "Аренда vs Продажа",
    averagePrice: "Средняя цена",
    marketTrends: "Тренды рынка",
    yearlyGrowth: "Годовой рост",
    villaSales: "Продажа вилл",
    villaRentals: "Аренда вилл",
    available: "Доступно",
    forSale: "Продажа",
    forRent: "Аренда",
    liveData: "Живые данные рынка",
    activeBuyers: "Активные покупатели",
    monthlyPerformance: "Ежемесячные показатели",
    units: "ед.",
    projectedGrowth: "Прогноз роста рынка",
    marketPrediction: "Прогноз рынка указывает на сильный рост на 15% в северном секторе Эр-Рияда к 4 кварталу 2025 года.",
  },
  AR: {
    login: "تسجيل الدخول",
    navLatest: "المشاريع المختارة",
    navPremium: "اختياراتنا الفاخرة",
    navMap: "خريطة الفيلات",
    navNews: "أخبار السوق",
    inquiry: "استفسار",

    bannerTitle: "أكثر من مجرد جدران",
    bannerSubtitle: "اكتشف حياة من الانسجام",
    bannerLocation: "الموقع",
    bannerLocationValue: "الرياض، السعودية",
    bannerCheckIn: "تاريخ الوصول",
    bannerCheckOut: "تاريخ المغادرة",
    bannerDates: "إضافة تواريخ",
    bannerRooms: "الغرف والضيوف",
    bannerRoomsValue: "غرفة 1، بالغ 1",
    bannerSearch: "بحث",
    bannerAll: "الكل",
    bannerVillas: "فيلات",
    bannerApartments: "شقق",
    bannerEstates: "مجمعات",
    bannerPenthouses: "بنتهاوس",
    bannerTownhouses: "تاون هاوس",

    latestProjects: "أحدث المشاريع",
    viewAll: "عرض جميع المشاريع",
    beds: "غرف النوم",
    baths: "الحمامات",
    soldStatus: "نسبة البيع",

    premiumListing: "إعلانات مميزة",
    premiumInquiry: "الاستفسارات والكونسيرج",
    premiumCurate: "دعنا نصمم أسلوب حياتك المثالي",
    premiumRequestInfo: "طلب معلومات",
    premiumSubtitle: "سيتواصل معك خبراؤنا في غضون 24 ساعة لتقديم استشارة شخصية.",
    premiumName: "الاسم الكامل",
    premiumPhone: "رقم الهاتف",
    premiumEmail: "البريد الإلكتروني",
    premiumInterest: "الاهتمام",
    premiumMessage: "رسالتك...",
    premiumSend: "إرسال الاستفسار",
    premiumSuccess: "تم استلام الطلب",
    premiumSuccessMsg: "شكراً لاهتمامك. سيتواصل معك أحد مستشارينا قريباً.",
    premiumBack: "العودة إلى النموذج",

    mapTitle: "أبرز المواقع",
    mapLocationOverview: "الموقع المختار",
    mapFilters: "فلاتر البحث",
    mapStatus: "حالة المشروع",
    mapReset: "إعادة تعيين الكل",
    mapNoResults: "لا توجد فيلات مطابقة",
    mapNoResultsSub: "حاول ضبط الفلاتر أو اختيار فئة أخرى لرؤية النتائج.",
    bookViewing: "حجز موعد مشاهدة",
    Buy: "شراء",
    Rent: "إيجار",
    "Buy Property": "شراء العقار",
    "Rent Property": "تأجير العقار",
    "Submit Buy Request": "إرسال الطلب",
    "Submit Rent Request": "إرسال الطلب",
    Success: "تم بنجاح",
    moveInDate: "تاريخ الانتقال",
    duration: "مدة الإيجار",
    optional: "اختياري",
    Close: "إغلاق",

    latestNews: "آخر الأخبار",
    readMore: "اقرأ المزيد",

    footerDescription: "تتميز شركة الرياض روف العقارية في تسويق العقارات الحديثة، معتمدة على قاعدة بيانات واسعة وفريق خبير للترويج للمشاريع بفعالية.",
    footerQuickLinks: "روابط سريعة",
    footerServices: "خدماتنا",
    footerContact: "اتصل بنا",
    footerInterested: "مهتم؟",
    footerRights: "© 2025 الرياض روف. جميع الحقوق محفوظة.",
    footerHome: "الرئيسية",
    footerProjects: "المشاريع",
    footerDevelopers: "المطورون",
    footerNews: "أخبار",
    footerOffPlan: "البيع على الخارطة",
    footerLands: "الأراضي",
    footerCashback: "كاش باك رمضان",
    footerApproach: "نهجنا",
    footerPrivacy: "سياسة الخصوصية",
    footerTerms: "الشروط والأحكام",

    navSale: "بيع",
    navRent: "إيجار",
    navNewBuildings: "مباني جديدة",
    navSpecialOffers: "عروض خاصة",

    formBuy: "شراء",
    formRent: "إيجار",
    formType: "نوع العقار",
    formCity: "المدينة",
    formRooms: "غرف",
    formAny: "أي",
    formPriceFrom: "السعر من",
    formPriceTo: "السعر حتى",
    formSearch: "بحث",
    formApartment: "شقة",
    formVilla: "فيلا",
    formTownhouse: "تاونهاوس",
    formCommercial: "تجاري",
    formLand: "أرض",
    checkHasPhoto: "يوجد صورة",
    checkNewBuilding: "مبنى جديد",
    checkFromOwner: "من المالك",
    checkCommercialFilter: "تجاري",

    specialOffers: "عروض خاصة",
    specialOffersSubtitle: "عروض ترويجية وخصومات خاصة لك.",
    offerCta: "عرض العرض",

    hotDeals: "عروض مميزة",
    hotDealsSubtitle: "إعلانات العقارات في الرياض",
    hotDealsSale: "للبيع",
    hotDealsRent: "للإيجار",
    hotDealsApartments: "شقق",
    hotDealsLands: "أراضي",
    hotDealsVillas: "فيلات",
    hotDealsCommercial: "تجاري",
    hotDealsRooms: "غرف",
    hotDealsViewAll: "عرض الكل",
    "add PropertyBtn": "إضافة عقار",

    offer1Tagline: "عرض موسمي",
    offer1Headline: "شروط رائعة. فيلا رائعة.",
    offer1Desc: "وفر 15٪ على فيلا تطل على المدينة - هذا الشهر فقط.",
    offer2Tag: "مبنى جديد",
    offer2Tagline: "مباشرة من المطور",
    offer2Headline: "شقة حديثة في KAFD.",
    offer2Desc: "شقق في المركز المالي بالرياض مع تقسيط حتى 5 سنوات.",
    offer3Tag: "حصري",
    offer3Tagline: "فقط معنا",
    offer3Headline: "بنتهاوس في Al Narjis Heights.",
    offer3Desc: "إطلالات بانورامية، تراس خاص، تشطيب كامل. أفضل سعر في الموسم.",
    Analytics: "التحليلات",
    priceAnalytics: "تحليلات السوق",
    rentVsSale: "الإيجار مقابل البيع",
    averagePrice: "متوسط السعر",
    marketTrends: "اتجاهات السوق",
    yearlyGrowth: "النمو السنوي",
    villaSales: "مبيعات الفلل",
    villaRentals: "إيجارات الفلل",

    Authenticated: "تم التحقق من الهوية",
    Logout: "تسجيل الخروج",
    Profile: "الملف الشخصي",
    InfinityPool: "مسبح لا متناهي",
    SmartHome: "منزل ذكي",
    HomeGym: "صالة رياضية منزلية",
    Security: "أمن على مدار الساعة",
    GardenArea: "منطقة حدائق",
    PrivateParking: "موقف سيارات خاص",
    Wifi: "إنترنت واي فاي",
    AC: "تكييف هواء",
    Location: "الموقع",
    Riyadh: "الرياض",
    AboutProperty: "نبذة عن العقار",
    returnToProjects: "عودة",
    Contact: "تواصل",
    salePrice: 'ثمن البيع',
    rentalPrice: 'سعر الإيجار',

    from: 'من',
    to: 'إلى',


  },
  ES: {
    login: "Acceso",
    navLatest: "Proyectos Recientes",
    navPremium: "Selección Premium",
    navMap: "Mapa de Villas",
    navNews: "Noticias del Mercado",
    inquiry: "Consulta",

    bannerTitle: "Más que solo paredes",
    bannerSubtitle: "Descubre una vida en armonía",
    bannerLocation: "Ubicación",
    bannerLocationValue: "Riad, SA",
    bannerCheckIn: "Entrada",
    bannerCheckOut: "Salida",
    bannerSearch: "Buscar",
    bannerAll: "Todo",
    bannerVillas: "Villas",
    bannerApartments: "Apartamentos",
    bannerEstates: "Fincas",
    bannerPenthouses: "Áticos",
    bannerTownhouses: "Casas adosadas",

    latestProjects: "Últimos Proyectos",
    viewAll: "Ver todos los proyectos",
    beds: "Habitaciones",
    baths: "Baños",
    soldStatus: "Estado de venta",

    premiumListing: "Listado Premium",
    premiumInquiry: "Consulta y Conserje",
    premiumCurate: "Permítanos curar el estilo de vida de sus sueños",
    premiumRequestInfo: "Solicitar información",
    premiumSubtitle: "Nuestros expertos se pondrán en contacto con usted en un plazo de 24 horas para ofrecerle una consulta personalizada.",
    premiumName: "Nombre completo",
    premiumPhone: "Número de teléfono",
    premiumEmail: "Correo electrónico",
    premiumInterest: "Interés",
    premiumMessage: "Tu mensaje...",
    premiumSend: "ENVIAR CONSULTA",
    premiumSuccess: "Solicitud recibida",
    premiumSuccessMsg: "Gracias por su interés. Uno de nuestros consultores premium se pondrá en contacto con usted en breve.",
    premiumBack: "Volver al formulario",

    mapTitle: "Principales señales visuales",
    mapLocationOverview: "Ubicación seleccionada",
    mapFilters: "Filtros de búsqueda",
    mapStatus: "Estado del proyecto",
    mapReset: "Restablecer todo",
    mapNoResults: "No hay villas coincidentes",
    mapNoResultsSub: "Intente ajustar sus filtros o selección de estado para ver más resultados.",
    bookViewing: "Reservar visita",

    latestNews: "Últimas noticias",
    readMore: "Leer más",

    footerDescription: "RIYADHRF Real Estate sobresale en el marketing inmobiliario moderno, aprovechando una vasta base de datos de clientes y un equipo de expertos para promover proyectos de manera efectiva.",
    footerQuickLinks: "Enlaces rápidos",
    footerServices: "Servicios",
    footerContact: "Contacto",
    footerInterested: "¿Interesado?",
    footerRights: "© 2025 RiyadhRoof. Todos los derechos reservados.",
    footerHome: "Inicio",
    footerProjects: "Proyectos",
    footerDevelopers: "Desarrolladores",
    footerNews: "Noticias",
    footerOffPlan: "Ventas fuera de plano",
    footerLands: "Tierras",
    footerCashback: "Ramadán Cashback",
    footerApproach: "Nuestro enfoque",
    footerPrivacy: "Política de privacidad",
    footerTerms: "Términos y condiciones",

    navSale: "Venta",
    navRent: "Alquiler",
    navNewBuildings: "Obra nueva",
    navSpecialOffers: "Ofertas especiales",

    formBuy: "Comprar",
    formRent: "Alquilar",
    formType: "Tipo de inmueble",
    formCity: "Ciudad",
    formRooms: "Habitaciones",
    formAny: "Cualquiera",
    formPriceFrom: "Precio desde",
    formPriceTo: "Precio hasta",
    formSearch: "Buscar",
    formApartment: "Apartamento",
    formVilla: "Villa",
    formTownhouse: "Adosado",
    formCommercial: "Comercial",
    formLand: "Terreno",
    checkHasPhoto: "Con foto",
    checkNewBuilding: "Obra nueva",
    checkFromOwner: "Del propietario",
    checkCommercialFilter: "Comercial",

    specialOffers: "Ofertas especiales",
    specialOffersSubtitle: "Promociones y ofertas exclusivas para usted.",
    offerCta: "Ver oferta",

    hotDeals: "Ofertas calientes",
    hotDealsSubtitle: "Anuncios inmobiliarios en Riad",
    hotDealsSale: "En venta",
    hotDealsRent: "En alquiler",
    hotDealsApartments: "Apartamentos",
    hotDealsLands: "Terrenos",
    hotDealsVillas: "Villas",
    hotDealsCommercial: "Comercial",
    hotDealsRooms: "Habitaciones",
    hotDealsViewAll: "Ver todo",
    Analytics: "Analítica",
    priceAnalytics: "Análisis de Mercado",
    rentVsSale: "Alquiler vs Venta",
    averagePrice: "Precio Promedio",
    marketTrends: "Tendencias",
    yearlyGrowth: "Crecimiento Anual",
    villaSales: "Ventas de Villas",
    villaRentals: "Alquiler de Villas",
  },
  PT: {
    login: "Conectarse",
    navLatest: "Projetos Recentes",
    navPremium: "Seleção Premium",
    navMap: "Mapa de Villas",
    navNews: "Notícias do Mercado",
    inquiry: "Inquérito",

    bannerTitle: "Mais do que apenas paredes",
    bannerSubtitle: "Descubra uma vida de harmonia",
    bannerLocation: "Localização",
    bannerLocationValue: "Riade, SA",
    bannerCheckIn: "Check In",
    bannerCheckOut: "Check Out",
    bannerSearch: "Pesquisar",
    bannerAll: "Tudo",
    bannerVillas: "Villas",
    bannerApartments: "Apartamentos",
    bannerEstates: "Propriedades",
    bannerPenthouses: "Coberturas",
    bannerTownhouses: "Moradias em banda",

    latestProjects: "Últimos Projetos",
    viewAll: "Ver todos os projetos",
    beds: "Quartos",
    baths: "Casas de banho",
    soldStatus: "Status de venda",

    premiumListing: "Listagem Premium",
    premiumInquiry: "Consulta e Concierge",
    premiumCurate: "Deixe-nos curar o estilo de vida dos seus sonhos",
    premiumRequestInfo: "Solicitar informações",
    premiumSubtitle: "Os nossos especialistas entrarão em contacto consigo no prazo de 24 horas para fornecer uma consulta personalizada.",
    premiumName: "Nome completo",
    premiumPhone: "Número de telefone",
    premiumEmail: "Endereço de e-mail",
    premiumInterest: "Interesse",
    premiumMessage: "Sua mensagem...",
    premiumSend: "ENVIAR INQUÉRITO",
    premiumSuccess: "Pedido Recebido",
    premiumSuccessMsg: "Obrigado pelo seu interesse. Um dos nossos consultores premium entrará em contacto consigo em breve.",
    premiumBack: "Voltar ao formulário",

    mapTitle: "Principais sinais para ver",
    mapLocationOverview: "Localização selecionada",
    mapFilters: "Filtros de pesquisa",
    mapStatus: "Status do projeto",
    mapReset: "Redefinir tudo",
    mapNoResults: "Sem moradias correspondentes",
    mapNoResultsSub: "Tente ajustar os seus filtros ou seleção de status para ver mais resultados.",
    bookViewing: "Agendar visita",

    latestNews: "Últimas Notícias",
    readMore: "Leia mais",

    footerDescription: "A RIYADHRF Real Estate destaca-se no marketing imobiliário moderno, aproveitando uma vasta base de datos de clientes e uma equipa de especialistas para promover projetos de forma eficaz.",
    footerQuickLinks: "Links Rápidos",
    footerServices: "Serviços",
    footerContact: "Contacto",
    footerInterested: "Interessado?",
    footerRights: "© 2025 RiyadhRoof. Todos os derechos reservados.",
    footerHome: "Início",
    footerProjects: "Projetos",
    footerDevelopers: "Desenvolvedores",
    footerNews: "Notícias",
    footerOffPlan: "Vendas fora do plano",
    footerLands: "Terras",
    footerCashback: "Ramadão Cashback",
    footerApproach: "Nossa Abordagem",
    footerPrivacy: "Política de Privacidade",
    footerTerms: "Termos e Condições",

    navSale: "Venda",
    navRent: "Aluguel",
    navNewBuildings: "Novos edifícios",
    navSpecialOffers: "Ofertas especiais",

    formBuy: "Comprar",
    formRent: "Alugar",
    formType: "Tipo de imóvel",
    formCity: "Cidade",
    formRooms: "Quartos",
    formAny: "Qualquer",
    formPriceFrom: "Preço a partir de",
    formPriceTo: "Preço até",
    formSearch: "Pesquisar",
    formApartment: "Apartamento",
    formVilla: "Villa",
    formTownhouse: "Moradia",
    formCommercial: "Comercial",
    formLand: "Terreno",
    checkHasPhoto: "Com foto",
    checkNewBuilding: "Novo edifício",
    checkFromOwner: "Do proprietário",
    checkCommercialFilter: "Comercial",

    specialOffers: "Ofertas especiais",
    specialOffersSubtitle: "Promoções e ofertas exclusivas para você.",
    offerCta: "Ver oferta",

    hotDeals: "Ofertas imperdíveis",
    hotDealsSubtitle: "Imóveis em Riade",
    hotDealsSale: "À venda",
    hotDealsRent: "Para alugar",
    hotDealsApartments: "Apartamentos",
    hotDealsLands: "Terrenos",
    hotDealsVillas: "Villas",
    hotDealsCommercial: "Comercial",
    hotDealsRooms: "Quartos",
    hotDealsViewAll: "Ver tudo",
    Analytics: "Análise",
    priceAnalytics: "Análise de Mercado",
    rentVsSale: "Aluguel vs Venda",
    averagePrice: "Preço Médio",
    marketTrends: "Tendências",
    yearlyGrowth: "Crescimento Anual",
    villaSales: "Vendas de Villas",
    villaRentals: "Aluguéis de Villas",
  },
  FR: {
    login: "Connexion",
    navLatest: "Projets Récents",
    navPremium: "Sélection Premium",
    navMap: "Carte des Villas",
    navNews: "Infos Marché",
    inquiry: "Demande",

    bannerTitle: "Plus que de simples murs",
    bannerSubtitle: "Découvrez une vie d'harmonie",
    bannerLocation: "Emplacement",
    bannerLocationValue: "Riyad, AR",
    bannerCheckIn: "Arrivée",
    bannerCheckOut: "Départ",
    bannerSearch: "Rechercher",
    bannerAll: "Tout",
    bannerVillas: "Villas",
    bannerApartments: "Appartements",
    bannerEstates: "Domaines",
    bannerPenthouses: "Penthouses",
    bannerTownhouses: "Maisons de ville",

    latestProjects: "Derniers Projets",
    viewAll: "Voir tous les projets",
    beds: "Chambres",
    baths: "Salles de bain",
    soldStatus: "Statut de vente",

    premiumListing: "Annonce Premium",
    premiumInquiry: "Demande & Conciergerie",
    premiumCurate: "Laissez-nous organiser le style de vie de vos rêves",
    premiumRequestInfo: "Demander des informations",
    premiumSubtitle: "Nos experts vous recontacteront sous 24 heures pour une consultation personnalisée.",
    premiumName: "Nom complet",
    premiumPhone: "Numéro de téléphone",
    premiumEmail: "Adresse e-mail",
    premiumInterest: "Intérêt",
    premiumMessage: "Votre message...",
    premiumSend: "ENVOYER LA DEMANDE",
    premiumSuccess: "Demande Reçue",
    premiumSuccessMsg: "Merci de votre intérêt. L'un de nos conseillers premium vous contactera prochainement.",
    premiumBack: "Retour au formulaire",

    mapTitle: "Principaux signes à voir",
    mapLocationOverview: "Emplacement sélectionné",
    mapFilters: "Filtres de recherche",
    mapStatus: "Statut du projet",
    mapReset: "Tout réinitialiser",
    mapNoResults: "Aucune villa correspondante",
    mapNoResultsSub: "Essayez d'ajuster vos filtres ou votre sélection de statut pour voir plus de résultats.",
    bookViewing: "Réserver une visite",

    latestNews: "Dernières Nouvelles",
    readMore: "Lire la suite",

    footerDescription: "RIYADHRF Real Estate excelle dans le marketing immobilier moderne, en s'appuyant sur une vaste base de données clients et une équipe d'experts pour promouvoir efficacement les projets.",
    footerQuickLinks: "Liens rapides",
    footerServices: "Services",
    footerContact: "Contact",
    footerInterested: "Intéressé ?",
    footerRights: "© 2025 RiyadhRoof. Tous droits réservés.",
    footerHome: "Accueil",
    footerProjects: "Projets",
    footerDevelopers: "Développeurs",
    footerNews: "Nouvelles",
    footerOffPlan: "Ventes sur plan",
    footerLands: "Terrains",
    footerCashback: "Ramadan Cashback",
    footerApproach: "Notre approche",
    footerPrivacy: "Politique de confidentialité",
    footerTerms: "Conditions générales",

    navSale: "Vente",
    navRent: "Location",
    navNewBuildings: "Nouvelles constructions",
    navSpecialOffers: "Offres spéciales",

    formBuy: "Acheter",
    formRent: "Louer",
    formType: "Type de bien",
    formCity: "Ville",
    formRooms: "Pièces",
    formAny: "Tout",
    formPriceFrom: "Prix à partir de",
    formPriceTo: "Prix jusqu'à",
    formSearch: "Rechercher",
    formApartment: "Appartement",
    formVilla: "Villa",
    formTownhouse: "Maison de ville",
    formCommercial: "Commercial",
    formLand: "Terrain",
    checkHasPhoto: "Avec photo",
    checkNewBuilding: "Nouvelle construction",
    checkFromOwner: "Du propriétaire",
    checkCommercialFilter: "Commercial",
    Analytics: "Analytique",
    priceAnalytics: "Analyse du Marché",
    rentVsSale: "Location vs Vente",
    averagePrice: "Prix Moyen",
    marketTrends: "Tendances",
    yearlyGrowth: "Croissance Annuelle",
    villaSales: "Ventes de Villas",
    villaRentals: "Locations de Villas",

    specialOffers: "Offres spéciales",
    specialOffersSubtitle: "Promotions et offres exclusives pour vous.",
    offerCta: "Voir l'offre",

    hotDeals: "Bonnes affaires",
    hotDealsSubtitle: "Annonces immobilières à Riyad",
    hotDealsSale: "À vendre",
    hotDealsRent: "À louer",
    hotDealsApartments: "Appartements",
    hotDealsLands: "Terrains",
    hotDealsVillas: "Villas",
    hotDealsCommercial: "Commercial",
    hotDealsRooms: "Chambres",
    hotDealsViewAll: "Voir tout",
  },
  HI: {
    login: "लॉगिन करें",
    navLatest: "नवीनतम परियोजनाएं",
    navPremium: "प्रीमियम चयन",
    navMap: "विला मानचित्र",
    navNews: "बाज़ार समाचार",
    inquiry: "पूछताछ",

    bannerTitle: "सिर्फ दीवारों से कहीं अधिक",
    bannerSubtitle: "सामंजस्यपूर्ण जीवन की खोज करें",
    bannerLocation: "स्थान",
    bannerLocationValue: "रियाद, सऊदी अरब",
    bannerCheckIn: "चेक-इन",
    bannerCheckOut: "चेक-आउट",
    bannerSearch: "खोजें",
    bannerAll: "सभी",
    bannerVillas: "विला",
    bannerApartments: "अपार्टमेंट",
    bannerEstates: "संपदा",
    bannerPenthouses: "पेंटहाउस",
    bannerTownhouses: "टाउनहाउस",

    latestProjects: "नवीनतम परियोजनाएं",
    viewAll: "सभी परियोजनाएं देखें",
    beds: "बेड",
    baths: "बाथ",
    soldStatus: "बिक्री की स्थिति",

    premiumListing: "प्रीमियम लिस्टिंग",
    premiumInquiry: "पूछताछ और कंसीयज",
    premiumCurate: "हमें आपके सपनों की जीवनशैली तैयार करने दें",
    premiumRequestInfo: "सूचना का अनुरोध करें",
    premiumSubtitle: "हमारे विशेषज्ञ व्यक्तिगत परामर्श प्रदान करने के लिए 24 घंटों के भीतर आपसे संपर्क करेंगे।",
    premiumName: "पूरा नाम",
    premiumPhone: "फ़ोन नंबर",
    premiumEmail: "ईमेल पता",
    premiumInterest: "रुचि",
    premiumMessage: "आपका संदेश...",
    premiumSend: "पूछताछ भेजें",
    premiumSuccess: "अनुरोध प्राप्त हुआ",
    premiumSuccessMsg: "आपकी रुचि के लिए धन्यवाद। हमारे प्रीमियम सलाहकारों में से एक जल्द ही आपसे संपर्क करेगा।",
    premiumBack: "फ़ॉर्म पर वापस जाएँ",

    mapTitle: "देखने के लिए शीर्ष संकेत",
    mapLocationOverview: "चयनित स्थान",
    mapFilters: "खोज फ़िल्टर",
    mapStatus: "परियोजना की स्थिति",
    mapReset: "सभी रीसेट करें",
    mapNoResults: "कोई मेल खाने वाला विला नहीं मिला",
    mapNoResultsSub: "अधिक परिणाम देखने के लिए अपने फ़िल्टर या स्थिति चयन को समायोजित करने का प्रयास करें।",
    bookViewing: "देखने के लिए बुक करें",

    latestNews: "नवीनतम समाचार",
    readMore: "अधिक पढ़ें",

    footerDescription: "RIYADHRF रियल एस्टेट आधुनिक रियल एस्टेट मार्केटिंग में उत्कृष्ट है, परियोजनाओं को प्रभावी ढंग से बढ़ावा देने के लिए एक विशाल क्लाइंट डेटाबेस और विशेषज्ञ टीम का लाभ उठाता है।",
    footerQuickLinks: "त्वरित लिंक",
    footerServices: "सेवाएं",
    footerContact: "संपर्क",
    footerInterested: "रुचि है?",
    footerRights: "© 2025 RiyadhRoof. सर्वाधिकार सुरक्षित।",
    footerHome: "होम",
    footerProjects: "परियोजनाएं",
    footerDevelopers: "विकासकर्ता",
    footerNews: "समाचार",
    footerOffPlan: "ऑफ-प्लान बिक्री",
    footerLands: "भूमि",
    footerCashback: "रमज़ान कैशबैक",
    footerApproach: "हमारा दृष्टिकोण",
    footerPrivacy: "गोपनीयता नीति",
    footerTerms: "नियम और शर्तें",

    navSale: "बिक्री",
    navRent: "किराया",
    navNewBuildings: "नई इमारतें",
    navSpecialOffers: "विशेष ऑफर",

    formBuy: "खरीदें",
    formRent: "किराए पर लें",
    formType: "संपत्ति का प्रकार",
    formCity: "शहर",
    formRooms: "कमरे",
    formAny: "कोई भी",
    formPriceFrom: "कीमत से",
    formPriceTo: "कीमत तक",
    formSearch: "खोजें",
    formApartment: "अपार्टमेंट",
    formVilla: "विला",
    formTownhouse: "टाउनहाउस",
    formCommercial: "व्यावसायिक",
    formLand: "भूखंड",
    checkHasPhoto: "फोटो सहित",
    checkNewBuilding: "नई इमारत",
    checkFromOwner: "मालिक से",
    checkCommercialFilter: "व्यावसायिक",
    Analytics: "विश्लेषण",
    priceAnalytics: "बाज़ार विश्लेषण",
    rentVsSale: "किराया बनाम बिक्री",
    averagePrice: "औसत मूल्य",
    marketTrends: "बाज़ार के रुझान",
    yearlyGrowth: "वार्षिक वृद्धि",
    villaSales: "विला बिक्री",
    villaRentals: "विला किराया",

    specialOffers: "विशेष ऑफर",
    specialOffersSubtitle: "आपके लिए प्रमोशन और एक्सक्लूसिव डील।",
    offerCta: "ऑफर देखें",

    hotDeals: "हॉट डील्स",
    hotDealsSubtitle: "रियाद में संपत्ति की लिस्टिंग",
    hotDealsSale: "बिक्री के लिए",
    hotDealsRent: "किराए के लिए",
    hotDealsApartments: "अपार्टमेंट",
    hotDealsLands: "भूखंड",
    hotDealsVillas: "विला",
    hotDealsCommercial: "व्यावसायिक",
    hotDealsRooms: "कमरे",
    hotDealsViewAll: "सब देखें",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("EN");
  const [isDark, setIsDark] = useState(() => {
    try {
      const saved = localStorage.getItem('theme');
      if (saved === null) return true;
      if (saved === "dark") return true;
      if (saved === "light") return false;
      return JSON.parse(saved);
    } catch (e) {
      return true;
    }
  });

  const [user, setUser] = useState(() => {
    try {
      const stored = localStorage.getItem('currentUser');
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  });

  useEffect(() => {
    localStorage.setItem('theme', JSON.stringify(isDark));
  }, [isDark]);

  const login = (userData) => {
    localStorage.setItem('currentUser', JSON.stringify(userData));
    setUser(userData);
  };

  const logout = () => {
    localStorage.removeItem('currentUser');
    setUser(null);
  };

  const updateUser = (updates) => {
    const updatedUser = { ...user, ...updates };
    localStorage.setItem('currentUser', JSON.stringify(updatedUser));
    setUser(updatedUser);

    try {
      const users = JSON.parse(localStorage.getItem('temp_users') || '[]');
      const userIndex = users.findIndex(u => u.email === user.email);
      if (userIndex !== -1) {
        users[userIndex] = updatedUser;
        localStorage.setItem('temp_users', JSON.stringify(users));
      }
    } catch (e) {
      console.error(e);
    }
  };

  const toggleTheme = () => setIsDark(prev => !prev);

  const t = (key) => translations[language]?.[key] || translations["EN"][key] || key;

  // Apply theme class to <html> for global CSS overrides
  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.remove('light-theme');
      document.documentElement.classList.add('dark-theme');
    } else {
      document.documentElement.classList.remove('dark-theme');
      document.documentElement.classList.add('light-theme');
    }
  }, [isDark]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isDark, toggleTheme, user, login, logout, updateUser }}>
      <div
        dir={language === "AR" ? "rtl" : "ltr"}
        style={{
          fontFamily:
            language === "AR" ? "'Cairo', sans-serif" :
              language === "HI" ? "'Noto Sans Devanagari', sans-serif" :
                "inherit"
        }}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
