import React, { createContext, useContext, useState, useEffect } from "react";

export const LanguageContext = createContext();

export const LanguageEN = {
    // Header
    login: "Login",
    addPropertyBtn: "Post an ad",
    navLatest: "Latest Projects",
    navPremium: "Premium Selection",
    navMap: "Villas Map",
    navNews: "Market News",
    inquiry: "Inquiry",

    // Banner
    bannerTitle: "More than just walls",
    bannerSubtitle: "Discover a life of harmony",
    bannerLocation: "Location",
    bannerLocationValue: "Riyadh, SA",
    bannerCheckIn: "Check In",
    bannerCheckOut: "Check Out",
    bannerDates: "Add Dates",
    bannerRooms: "Rooms and Guests",
    bannerRoomsValue: "1 rooms, 1 adults",
    bannerSearch: "Search",
    bannerAll: "All",
    bannerVillas: "Villas",
    bannerApartments: "Apartments",
    bannerEstates: "Estates",
    bannerPenthouses: "Penthouses",
    bannerTownhouses: "Townhouses",

    // LatestProjects
    latestProjects: "Latest Projects",
    viewAll: "View All Projects",
    beds: "Beds",
    baths: "Baths",
    soldStatus: "Sold Status",

    // PremiumListing
    premiumListing: "Premium Listing",
    premiumInquiry: "Inquiry & Concierge",
    premiumCurate: "Let Us Curate Your Dream Lifestyle",
    premiumRequestInfo: "Request Information",
    premiumSubtitle: "Our experts will get back to you within 24 hours to provide a personalized consultation.",
    premiumName: "Full Name",
    premiumPhone: "Phone Number",
    premiumEmail: "Email Address",
    premiumInterest: "Interest",
    premiumMessage: "Your Message...",
    premiumSend: "SEND INQUIRY",
    premiumSuccess: "Request Received",
    premiumSuccessMsg: "Thank you for your interest. One of our premium consultants will reach out to you shortly.",
    premiumBack: "Back to Form",

    // Map Section
    mapTitle: "Top Sign To See",
    mapLocationOverview: "Selected Location",
    mapFilters: "Search Filters",
    mapStatus: "Project Status",
    mapReset: "Reset All",
    mapNoResults: "No Matching Villas",
    mapNoResultsSub: "Try adjusting your filters or status selection to see more results.",
    bookViewing: "Book Viewing",
    Buy: "Buy",
    Rent: "Rent",
    "Buy Property": "Buy Property",
    "Rent Property": "Rent Property",
    "Submit Buy Request": "Submit Buy Request",
    "Submit Rent Request": "Submit Rent Request",
    Success: "Success",
    moveInDate: "Move-in Date",
    duration: "Duration",
    optional: "Optional",
    Close: "Close",
    available: "Available",
    availableProperties: "Available Villas",
    salePrice: "Sale Price",
    rentalPrice: "Rental Price",

    // News
    latestNews: "Latest News",
    readMore: "Read More",

    // Footer
    footerDescription: "RIYADHRF Real Estate excels in modern real estate marketing, leveraging a vast client database and expert team to promote projects effectively.",
    footerQuickLinks: "Quick Links",
    footerServices: "Services",
    footerContact: "Contact",
    footerInterested: "Interested?",
    footerRights: "© 2025 RiyadhRoof. All rights reserved.",
    footerHome: "Home",
    footerProjects: "Projects",
    footerDevelopers: "Developers",
    footerNews: "News",
    footerOffPlan: "Off-plan sales",
    footerLands: "Lands",
    footerCashback: "Ramadan Cashback",
    footerApproach: "Our Approach",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms & Conditions",


    // Navbar new links
    navSale: "Sale",
    navRent: "Rent",
    navNewBuildings: "New Buildings",
    navSpecialOffers: "Special Offers",

    // Search form
    formBuy: "Buy",
    formRent: "Rent",
    formType: "Property Type",
    formCity: "City",
    formRooms: "Rooms",
    formAny: "Any",
    formPriceFrom: "Price from",
    formPriceTo: "Price to",
    formSearch: "Search",
    formApartment: "Apartment",
    formVilla: "Villa",
    formTownhouse: "Townhouse",
    formCommercial: "Commercial",
    formLand: "Land",
    checkHasPhoto: "Has photo",
    checkNewBuilding: "New building",
    checkFromOwner: "From owner",
    checkCommercialFilter: "Commercial",
    Contact: "Contact",

    // Special Offers
    specialOffers: "Special Offers",
    specialOffersSubtitle: "Promotions and exclusive deals for you.",
    offerCta: "View Offer",

    // Hot Deals
    hotDeals: "Hot Deals",
    hotDealsSubtitle: "Real estate listings in Riyadh",
    hotDealsSale: "For Sale",
    hotDealsRent: "For Rent",
    hotDealsApartments: "Apartments",
    hotDealsLands: "Lands",
    hotDealsVillas: "Villas",
    hotDealsCommercial: "Commercial",
    hotDealsRooms: "Rooms",
    hotDealsViewAll: "View all",
    returnToProjects: "Return",

    // Special Offer content
    offer1Tagline: "Seasonal Offer",
    offer1Headline: "Great conditions. Great villa.",
    offer1Desc: "Save 15% on a villa with a city view — this month only.",
    offer2Tag: "New Building",
    offer2Tagline: "Direct from developer",
    offer2Headline: "Modern apartment in KAFD.",
    offer2Desc: "Apartments in Riyadh's financial district with up to 5-year installments.",
    offer3Tag: "Exclusive",
    offer3Tagline: "Only with us",
    offer3Headline: "Penthouse at Al Narjis Heights.",
    offer3Desc: "Panoramic views, private terrace, full finishing. Best price of the season.",

    // Advanced search
    moreSettings: "More settings",
    lessSettings: "Less settings",
    clearAll: "Clear all",
    showResults: "Show results",
    viewList: "List",
    viewMap: "Map",
    houseType: "House type",
    yearBuilt: "Year built",
    floor: "Floor",
    notFirst: "Not first",
    notLast: "Not last",
    totalArea: "Total area, m²",
    kitchenArea: "Kitchen area, m²",
    resComplex: "Residential complex",
    hotOffers: "Hot Offers",
    viewAllOffers: "View all",
    sortBy: "Sort by:",
    sortNew: "Newest",
    sortCheap: "Cheapest",
    sortExpensive: "Expensive",
    searchInThisSection: "Submit ad in this section",
    foundAds: "ads found",
    from: "From",
    to: "To",
    any: "Any",
    Analytics: "Analytics",
    priceAnalytics: "Market Analytics",
    rentVsSale: "Rent vs Sale",
    averagePrice: "Average Price",
    marketTrends: "Market Trends",
    yearlyGrowth: "Yearly Growth",
    villaSales: "Villa Sales",
    villaRentals: "Villa Rentals",
    forSale: "For Sale",
    forRent: "For Rent",
    liveData: "Live Market Data",
    activeBuyers: "Active Buyers",
    monthlyPerformance: "Monthly Performance",
    units: "units",
    projectedGrowth: "Projected Market Growth",
    marketPrediction: "Market prediction indicates a strong 15% growth in the North Riyadh sector by Q4 2025.",

    Authenticated: "Authenticated",
    Logout: "Logout",
    Profile: "Profile",
    InfinityPool: "Infinity Pool",
    SmartHome: "Smart Home",
    HomeGym: "Home Gym",
    Security: "Security 24/7",
    GardenArea: "Garden Area",
    PrivateParking: "Private Parking",
    Wifi: "High-Speed WiFi",
    AC: "Air Conditioning",
    Location: "Location",
    Riyadh: "Riyadh",
    AboutProperty: "About Property",
    Jan: "Jan", Feb: "Feb", Mar: "Mar", Apr: "Apr", May: "May", Jun: "Jun",
    Jul: "Jul", Aug: "Aug", Sep: "Sep", Oct: "Oct", Nov: "Nov", Dec: "Dec",

}